name: Shell Commands 

on:
  push:
    branches:
      - main

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 360 is the maximum number of minutes that the job can take 

    steps:
      - name: echo a String 
        run: echo "Hello Momo"
        continue-on-error: true # this allow the others steps to run even if this step failed (the number of minute before gethub kill the process)
      
      - name: multiline script
        run: |
          node -v
          npm -v

      - name: python command
        run: |
          import platform 
          print (platform.processor())
        shell: python

  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"] # This Job is depending on the run-shell-command job  

    steps:
      - name: Directory Powershell 
        run: Get-Location
      
      - name: Directory branches
        run: pwd
        shell: bash 

